"""Add table

Revision ID: 13407df3d4ab
Revises: 7fb24047cdcd
Create Date: 2024-05-27 22:58:16.361987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13407df3d4ab'
down_revision = '7fb24047cdcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('velocidad', sa.Float(), nullable=False),
    sa.Column('direccion', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viento')
    # ### end Alembic commands ###
