"""Add table

Revision ID: cbfdecae6f07
Revises: 
Create Date: 2024-05-27 22:51:54.922639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbfdecae6f07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clima',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tem_min', sa.Float(), nullable=False),
    sa.Column('tem_max', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clima')
    # ### end Alembic commands ###
